Transform: AWS::Serverless-2016-10-31
Resources:
  cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito/template.yaml
  api:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api/template.yaml
  dynamodb:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./dynamo/template.yaml
