Transform: AWS::Serverless-2016-10-31

Parameters:
  ENV:
    Type: String
    Description: Deployment environment
    AllowedValues:
      - "prod"
      - "test"
  AppName:
    Type: String
    Description: Name of the application
  AdminEmail:
    Type: String
    Description: Email address for the application admin
  ClientDomains:
    Type: String
    Description: Allowed callback URLs for authentication
  Domain:
    Type: String
    Description: Application domain name

Resources:
  dynamodb:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./dynamo/template.yaml
      Parameters:
        TableName: !Sub "${AppName}-db"

  cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito/template.yaml
      Parameters:
        TableName: !Sub "${AppName}-db"
        AppName: !Ref AppName
        ClientDomains: !Ref ClientDomains
        AdminEmail: !Ref AdminEmail
        AddGroupsToScopes: "true"

  api:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api/template.yaml
      Parameters:
        TableName: !Sub "${AppName}-db"
        UserPoolId: !GetAtt cognito.Outputs.UserPoolId
        Audience: !GetAtt cognito.Outputs.UserPoolClientId
        ENV: !Ref ENV
        Domain: !Ref Domain
