Transform: AWS::Serverless-2016-10-31

Parameters:
  AppName:
    Type: String
    Description: Name of the application
  AdminEmail:
    Type: String
    Description: Email address for the application admin

Resources:
  dynamodb:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./dynamo/template.yaml
      Parameters:
        TableName: !Sub "${AppName}-db"

  cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito/template.yaml
      Parameters:
        TableName: !Sub "${AppName}-db"
        AppName: !Ref AppName
        ClientDomains: "http://localhost:8080/oauth/callback,https://csclfg.com/oauth/callback,https://oauth.pstmn.io/v1/callback"
        AdminEmail: !Ref AdminEmail
        AddGroupsToScopes: "true"

  # api:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./api/template.yaml
