spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/studyseeking
    username: admin
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
