Transform: AWS::Serverless-2016-10-31

Parameters:
  ENV:
    Type: String
    Description: Which site to deploy
  AppDomain:
    Type: String
  AppName:
    Type: String
  ClientDomains:
    Type: String
    Description: Allowed callback URLs for authentication
  UserPoolId:
    Type: String
    Default: d
  UserPoolClientId:
    Type: String
    Default: d

Resources:
  dynamodb:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./dynamo/template.yaml
      Parameters:
        TableName: !Sub "${AppName}-db"

  api:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api/template.yaml
      Parameters:
        TableName: !Sub "${AppName}-db"
        UserPoolId: !GetAtt cognito.Outputs.UserPoolId
        Audience: !GetAtt cognito.Outputs.UserPoolClientId
        ENV: !Ref ENV
        Domain: !Ref AppDomain

  ui:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./ui/template.yaml
      Parameters:
        UserPoolId: !Ref UserPoolId
        Audience: !Ref UserPoolClientId
        ENV: !Ref ENV
        Domain: !Ref Domain
